Monitored tokens API group
ChainSafe/web3-circle-libs pull request #53
Opened 2024-12-03 22:32 UTC by avkos

Fixes #12

2024-12-04 14:49 UTC, danforbes requested changes
Can you give me some time to update the documentation before this is merged?

2024-12-05 02:17 UTC, avkos commented
> Can you give me some time to update the documentation before this is merged?

yes. for sure!

2024-12-06 16:38 UTC, danforbes approved these changes
Just a couple of questions. Please review [my recent commit](https://github.com/ChainSafe/web3-circle-libs/pull/53/commits/98cd387f5b16b6fbcac6a854d51be01c6cb88250) as I did make one small change to `index.ts` (changed `CircleSdk.monitoredTokensApi` to `CircleSdk.monitoredTokens` for consistency).

2024-12-06 16:38 UTC, danforbes commented on packages/web3-circle-sdk/src/types.ts
> +  pageSize?: number; // between 1 and 50, default is 10
Why isn't this type just composing `FilterPagesOptions` like the other types?

2024-12-06 16:38 UTC, danforbes commented on packages/web3-circle-sdk/src/types.ts
> +  scope: string;
Should this be the `MONITORED_TOKENS_SCOPE` enum instead of a string?

2024-12-10 14:55 UTC, merged