setup the React Components project
ChainSafe/web3-circle-libs pull request #60
Opened 2024-12-09 14:39 UTC by Muhammad-Altabba

2024-12-11 21:11 UTC, danforbes reviewed
I'm very unfamiliar with this type of project, so I've just added a few basic comments. What can I do to help document this project?

2024-12-11 21:11 UTC, danforbes commented on packages/circle-react-components/.nvmrc
> +v16.18.1
There are other parts of this project (`MAINTAINERS_NOTES` and `package.json`) that state that this project is using Node v20 or higher.

2024-12-11 21:11 UTC, danforbes commented on packages/circle-react-components/README.md
> +Note: You are welcome to contribute. And if you want to create an MR check the file ./MAINTAINERS_NOTES.md.
```suggestion
Note: You are welcome to contribute. And if you want to create a Pull Request check the file ./MAINTAINERS_NOTES.md.
```

2024-12-11 21:11 UTC, danforbes commented on .env.example
> +CIRCLE_API_KEY=
Does this belong in the repository root?

2024-12-12 08:46 UTC, krzysu requested changes
Hey, thanks for your effort on this PR, but I can’t accept it in its current state. I would suggest to recreate your branch from `main` because this PR includes commits that are already merged.

Also, I noticed modifications to files in `circle-demo-webapp` and `web3-circle-sdk`, as well as additional files shown in the screenshot below. Are they related to the setup of a new package? If not, could you clean this up and focus on providing a minimal package that exports a single component for publishing?

As a reference, you can copy one of the components from the demo app and test it manually end-to-end to ensure it works. Let me know if you need any help!

<img width="298" alt="Screenshot 2024-12-12 at 09 41 47" src="https://github.com/user-attachments/assets/124a34db-7790-4d0b-bac3-ca90c2263f2d" />

2024-12-17 14:53 UTC, krzysu commented
Hey @Muhammad-Altabba, I’ve improved my message, and I’m sorry for how the initial version came across. Let me know if you need any help!

2024-12-19 09:52 UTC, Muhammad-Altabba commented
No issues, many thanks Kris,
Sorry that, the MR contains lots of changes altogether because of the time limit. And there was also no description depending on the early verbal communication. But now I edited the description to have clarity. 

However, I will create separate MRs for each point to simplify the review. So we can review and discuss them separately. And I will start proposing the MRs that will affect the whole repo and its packages first.

2025-01-08 08:36 UTC, krzysu commented
I don't think we need this PR anymore, it's very much outdated.

2025-01-08 08:36 UTC, closed without merging